services:
  backend:
    build:
      context: ./server
    volumes:
        - ./hub.db:/app/hub.db
    environment:
      - CLIENT_URL=${CLIENT_URL}

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL}