services:
  backend:
    build:
      context: ./server
    volumes:
        - hub_db_data:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/hub.db
      - CLIENT_URL=${CLIENT_URL}

  frontend:
    build:
      context: ./client
      args:
        VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - backend
    environment:
      - VITE_API_URL=${VITE_API_URL}